name: skills_xorijdaish
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  flutter_spinkit: ^5.2.1
  intl_phone_field: ^3.2.0
  iconly: ^1.0.1
  google_nav_bar: ^5.0.7
  flutter_animate: ^4.5.2
  tab_indicator_styler: ^2.0.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  logger: ^2.6.0
  shimmer: ^3.0.0
  readmore:
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.2.5
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.0.0
  image_picker: ^1.1.2
  flutter_charts: ^0.5.2
  webview_flutter: ^4.13.0
  http: ^1.4.0
  flutter_switch: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  fl_chart: ^1.0.0
  video_player: ^2.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/

fonts:
  - family: Source Sans 3
    fonts:
      - asset: assets/fonts/SourceSans3-VariableFont_wght.ttf
