name: skills_xorijdaish
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  flutter_spinkit: ^5.2.1
  intl_phone_field: ^3.2.0
  iconly: ^1.0.1
  google_nav_bar: ^5.0.7
  flutter_animate: ^4.5.2
  tab_indicator_styler: ^2.0.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  logger: ^2.6.0
  shimmer: ^3.0.0
  readmore: ^3.0.0
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.2.5
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.0.0
  image_picker: ^1.1.2
  flutter_charts: ^0.5.2
  webview_flutter: ^4.13.0
  http: ^1.4.0
  flutter_switch: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  fl_chart: ^0.69.0
  video_player: ^2.10.0
  chewie: ^1.12.1
  cached_network_image: ^3.3.1
  syncfusion_flutter_pdfviewer: ^30.1.39
  url_launcher: ^6.2.5
  loading_indicator: ^3.1.1
  awesome_snackbar_content: ^0.1.6
  camera: ^0.11.2
  flutter_html: ^3.0.0
  another_flushbar: ^1.12.30
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  file_picker: ^10.2.0
  confetti: ^0.8.0
  flutter_cache_manager: ^3.4.1
  audioplayers: ^6.5.0
  carousel_slider: ^5.1.1
  open_filex: ^4.7.0
  path: ^1.9.1
  myid: ^1.4.1
  photo_view: ^0.15.0
  flutter_slidable: ^4.0.0
  flick_video_player: ^0.9.0
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^3.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/

fonts:
  - family: Source Sans 3
    fonts:
      - asset: assets/fonts/SourceSans3-VariableFont_wght.ttf
